name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout sshoogr
        uses: actions/checkout@v1
        with:
          path: main

      - name: Checkout sshoogr-parent
        uses: actions/checkout@v2
        with:
          repository: sshoogr/sshoogr-parent
          path: sshoogr-parent

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish sshoogr-parent
        uses: eskatos/gradle-command-action@v1
        with:
            arguments: publishToMavenLocal
            wrapper-cache-enabled: true
            dependencies-cache-enabled: true
            build-root-directory: ./sshoogr-parent

      - name: Build sshoogr
        uses: eskatos/gradle-command-action@v1
        with:
            arguments: build
            wrapper-cache-enabled: true
            dependencies-cache-enabled: true
            build-root-directory: .
