name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout sshoogr-parent
        uses: actions/checkout@v2
        with:
          repository: sshoogr/sshoogr-parent
          path: sshoogr-parent

      - name: Checkout sshoogr
        uses: actions/checkout@v1
        with:
          path: main

      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache gradle wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
          restore-keys: |
            ${{ runner.os }}-gradlew-

      - name: Grant execute permission to gradlew (1)
        run: chmod +x gradlew
        working-directory: ./sshoogr-parent

      - name: Grant execute permission to gradlew (2)
        run: chmod +x gradlew
        working-directory: ./main

      - name: Publish sshoogr-parent
        run: ./gradlew publishToMavenLocal
        working-directory: ./sshoogr-parent

      - name: Build sshoogr
        run: ./gradlew build
        working-directory: ./main
