name: Release

on:
  release:
    types: 
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      CI: true
      SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
          restore-keys: |
            ${{ runner.os }}-gradlew-
      - run: |
          sudo echo "deb [trusted=yes] https://apt.secrethub.io stable main" > secrethub.sources.list
          sudo mv secrethub.sources.list /etc/apt/sources.list.d/secrethub.sources.list
          sudo apt-get update
          sudo apt-get install -y secrethub-cli
          mkdir -p $HOME/.gradle
          secrethub read sshoogr/sshoogr/secring.gpg -o secring.gpg
          truncate --size=-1 secring.gpg
          secrethub inject -i gradle.properties.tmpl > $HOME/.gradle/gradle.properties
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: release
